version: '3.2'

networks: 
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  app:
    build:
        context: .
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks: 
      - app-network
    ports:
      - "80:80"
    environment:
      PORT: 80
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: 
      - app-network
  mailhog:
    image: mailhog/mailhog:latest
    ports:
        - "1025:1025"
        - "8025:8025"
    networks: 
      - app-network
