version: '3'

networks: 
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  app: 
    build:
        context: .
    restart: unless-stopped
    tty: true
    environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks: 
      - app-network

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: appetiser
      MYSQL_ROOT_PASSWORD: r00t
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db-data:/var/lib/mysql
    networks: 
      - app-network

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks: 
      - app-network